export enum ApiErrorCode {
	USER_NOT_FOUND = 'user-not-found',
	USER_UNEDITABLE = 'user-uneditable',
	USER_ALREADY_EXISTS = 'user-already-exists',
	EMAIL_ALREADY_EXISTS = 'email-already-exists',
	MISSING_CREDENTIALS = 'missing-credentials',
	WRONG_AUTH_METHOD = 'wrong-auth-method',
	ACCOUNT_DISABLED = 'account-disabled',
	WRONG_PASSWORD = 'wrong-password',
	TOKEN_NOT_FOUND = 'token-not-found',
	TOKEN_ALREADY_SENT = 'token-already-sent',
	INVALID_TOKEN = 'invalid-token',
	INVALID_CSRF_TOKEN = 'invalid-csrf-token',
	EMAIL_ALREADY_VERIFIED = 'email-already-verified',
	INVALID_INPUT = 'invalid-input',
	PASSWORD_REQUIRED = 'password-required',
	INTERNAL = 'internal-error',
	TOKEN_EXPIRED = 'token-expired',
	FILE_NOT_FOUND = 'file-not-found',
	WRONG_FILE_FORMAT = 'wrong-file-format',
	FILE_TOO_LARGE = 'file-too-large',
	SETTING_NOT_FOUND = 'setting-not-found',
};