name: Develop branch synchronization

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "contact@weberger.net"
      - name: Sync Develop Branch
        run: |
          git checkout main
          git fetch origin
          git checkout develop
          git pull
          git merge origin/main
          git push origin develop
