name: Develop branch synchronization

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync Develop Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout main
          git fetch origin
          git checkout develop
          git pull
          git merge origin/main
          git push origin develop